unifont_version = "16.0.03"

with open(r"C:\Users\q6027\Downloads\unifont-16.0.03.otf",'rb') as f:
    bts = f.read()

bts = [str(int(x)) for x in bts]
bts = ','.join(bts)

with open("unifont.inl",'w') as f:
    f.write("// this included file is generated by 'generate_unifont.py'\n")
    f.write("#define UNIFONT_VERSION \"" + unifont_version + "\"\n")
    f.write(f"uint8_t unifont[{len(bts)}] = " + "{" + str(bts) + "};\n")